package com.awverret.gymclimbtracker.model;

/**
 * Created by aubry on 2/24/17.
 */

public enum RopeGrade {
    FIVE_FIVE, FIVE_SIX, FIVE_SEVEN, FIVE_EIGHT, FIVE_NINE, FIVE_TEN_A, FIVE_TEN_B, FIVE_TEN_C, FIVE_TEN_D, FIVE_ELEVEN_A, FIVE_ELEVEN_B, FIVE_ELEVEN_C, FIVE_ELEVEN_D, FIVE_TWELVE_A, FIVE_TWELVE_B, FIVE_TWELVE_C, FIVE_TWELVE_D, FIVE_THIRTEEN_A, FIVE_THIRTEEN_B, FIVE_THIRTEEN_C, FIVE_THIRTEEN_D, FIVE_FOURTEEN
}
